config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tassets#index'

  get '/tassets' => 'tassets#index'
  get '/tassets/critical' => 'tassets#critical', :as => :critical_tassets
  get '/tassets/parents' => 'tassets#parents', :as => :parent_tassets
  
  get '/tclasses' => 'tclasses#index'
  get '/tclasses/:id' => 'tclasses#show', :as => :tclasses_assets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset_status.rb
class AssetStatus < ApplicationRecord

    def self.load_from_json(hash) 
        hash.keys.each do |k| 
            a = AssetStatus.create( :description => k, :code => hash[k] )
            puts "#{a.errors.full_messages}" if !a.valid?
        end
    end

    def self.get_description(code) 
        as = AssetStatus.find_by(:code => code)
        as ? as.description : "unknown"
    end

    def self.get_code(description)
        as = AssetStatus.find_by(:description => description)
        as ? as.code : 0
    end
end

app/models/parental_relation.rb
class ParentalRelation < ApplicationRecord
    belongs_to :t_asset, :class_name => "TAsset"
    belongs_to :child, :class_name => "TAsset"
end

app/models/property.rb
class Property < ApplicationRecord
    validates :property_id, presence: true, uniqueness: true 

end

app/models/t_asset.rb
class TAsset < ApplicationRecord
    validates :asset_id, presence: true, uniqueness: true   

    has_and_belongs_to_many :t_classes

    has_many :parental_relations
    has_many :parent, :class_name => "TAsset"
    has_many :children, :through => :parental_relations, :class_name => "TAsset"

    def self.create_from_json asset_hash
        asset = TAsset.create( 
            :asset_id => asset_hash['assetId'], 
            :name => asset_hash['name'],
            :description => asset_hash['description'],
            :status => asset_hash['status'],
            :icon => asset_hash['icon'],
            :parent_asset_id => asset_hash['parentId']
        )
        asset_hash['classList'].each { |c|
            asset_class = TClass.find_or_create_by(class_id: c['id']) do |tc|
                tc.name = c['name']
                tc.drill = c['drill']
            end
            asset.t_classes << asset_class
        }

        # To Do: not handling property references - :running, :utilization, :performance, :location
        asset.save
        asset
    end
end

app/models/t_class.rb
class TClass < ApplicationRecord
    validates :class_id, presence: true, uniqueness: true 

    has_and_belongs_to_many :t_assets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
end

app/controllers/tassets_controller.rb
class TassetsController < ApplicationController
    def index
        # ToDo: search getting complicated.  Maybe move to model...
        # especially if dealing with user syntax (?) to SQL syntax (%)
        @search_field = params[:search] ? params[:search] : "id"
        if params[:search]
            puts "Searching for #{params["search"]} #{params["value"]}"
            if params["search"] == "status"
                params["value"] = AssetStatus.get_code(params["value"])
            end
            @assets = TAsset.where(query_string(params["search"]), params["value"])
        else
            @assets = TAsset.all 
        end
    end

    def critical
        @assets = TAsset.where( status: '3' ).all
    end

    private
    # why doing this weird thing?  Because the ? won't work for
    # the column name (SQL treating the column and value name strings differently)
    # A more secure approach would be to assign query string in case statement
    # (so we are sure search_field is valid)
    def query_string search_field
        "#{search_field} LIKE ?"
    end
end

app/controllers/tclasses_controller.rb
class TclassesController < ApplicationController
    def index
        @class_count = TClass.all.count;
        @class_name_count = TClass.distinct.count(:name) 
        # ASSUMPTION : all classes have unique names!
        @classes = TClass.all
    end

    def show
        @class = TClass.find_by(:id => params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # asset index search helpers
    def search_select_tag (search_field)
        fields= [{value: '', display: 'Choose Search Field'}, 
                 {value: 'asset_id', display: 'Id'},
                 {value: 'name', display: 'Name'}, 
                 {value: 'description', display: 'Description'},
                 {value: 'status', display: 'Status'}, 
                 {value: 'icon', display: 'Icon'},                                           
                 {value: 'parent_asset_id', display: 'Parent Id'}]
    
        html = "<select name='search' id='search'>"
        fields.each do |field|
            html += "<option #{search_selected_option(field[:value], search_field)} "
            html += " value=#{field[:value]}>#{field[:display]}</option>"
        end
        html.html_safe
    end
    
    def search_selected_option(field, search_field)
        field==search_field ? "selected='selected'" : ""
    end

    # status lookup
    def lookup_status (c)
        AssetStatus.get_description(c)
    end
end

app/helpers/tassets_helper.rb
module TassetsHelper
end

app/helpers/tclasses_helper.rb
module TclassesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwinThread</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
    <h4 class="logo">TwinThread</h4>
      <ul class="nav-links">
        <li class="nav-item"><a href=<%= tassets_path %>>Assets</a></li>
        <li class="nav-item"><a href=<%= critical_tassets_path %>>Critical</a></li>
        <li class="nav-item"><a href=<%= tclasses_path %>>Classes</a></li>
        <li class="nav-item"><a href=<%= parent_tassets_path %>>Parents</a></li>
      </ul>
    </nav>

    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tassets/critical.html.erb
<div class="page-container">
    <h1>Critical Assets</h1>
    <div>
        <table id="assets">
            <thead>
                <tr>
                    <th scope="col">Asset Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Status</th>
                    <th scope="col">Icon</th>
                    <th scope="col">Parent</th>
                </tr>
            </thead>
            <tbody>
                <% @assets.each do | asset| %>
                    <tr>
                        <td><%= asset.asset_id %></td>
                        <td><%= asset.name%></td>
                        <td><%= asset.description %></td>
                        <td><%= lookup_status asset.status %></td>       
                        <td><%= asset.icon %></td>
                        <td><%= asset.parent_asset_id %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
  </div>

app/views/tassets/index.html.erb
<h1>Assets Index</h1>
<div class="page-container">
    <div>
        <table id="assets">
            <thead>
                <tr>
                    <th scope="col">Asset Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Status</th>
                    <th scope="col">Icon</th>
                    <th scope="col">Parent</th>
                    <th scope="col">Classes</th>
                </tr>
            </thead>
            <tbody>
                <% @assets.each do | asset| %>
                    <tr>
                        <td><%= asset.asset_id %></td>
                        <td><%= asset.name%></td>
                        <td><%= asset.description %></td>
                        <td><%= asset.status %></td>       
                        <td><%= asset.icon %></td>
                        <td><%= asset.parent_asset_id %></td>
                        <td><% asset.t_classes.each do |c| %>
                            <%= c.name %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
  </div>

app/views/tassets/parents.html.erb
<div>
    <h1>Assets by Parent Listing</h1>
    <ul>
        <% @parents.each do |parent| %>
            <li>
                <%= parent.asset_id %> - <%= parent.name %>
                <p>
                <% parent.children.each do |child| %>
                    child: <%= child.asset_id %>-<%= child.name %>, 
                <% end %>
                </p>
            </li>
        <% end %>
    </ul>
</div>

app/views/tclasses/index.html.erb
<div class="page-container">
    <h1>Classes</h1>
    <p>Number of Classes: <%= @class_count %></p>
    <p>Number of Unique Class Names: <%= @class_name_count %></p>
    <div>
        <table id="classes">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Drill</th>
                    <th scope="col">Assets</th>
                </tr>
            </thead>
            <tbody>
                <% @classes.each do | c| %>
                    <tr>
                        <td><%= c.class_id %></td>
                        <td><%= c.name %></td>
                        <td><%= c.drill %></td>
                        <td><%= link_to "View", tclasses_assets_path(c.id) %></td>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
 

app/views/tclasses/show.html.erb
<div class="page-container">
    <h1>Class: <%=@class.name %></h1>
    <p>
        Id: <%= @class.class_id %><br/>
        Name: <%= @class.name %><br/>
        Drill: <%= @class.drill %>
    </p>
    <div id="class_asset_list">
        <h2>Assets (count=<%=@class.t_assets.count%>)</h2>
        <ol>
            <% @class.t_assets.each do | a | %>
                <li><%= a.name %></li>
            <% end %>
        </ol>
    </div>
</div> 